name: "Tristan's Code Blog"
description: "Coding notes dumping ground"

url: "https://tmorse7.github.io/Apprenticeship/"

gems: [jekyll-paginate]
paginate: 10

markdown: rdiscount
permalink: pretty
